name: QuantumPunish
version: '2.1.0'
main: me.bintanq.quantum.QuantumPunish
api-version: '1.21'
author: bintanq
description: Quantum punishment system with Discord integration
website: https://github.com/bintanq/quantumpunish
softdepend: [PlaceholderAPI]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.1.0

commands:
  quantumpunish:
    description: Main plugin command
    aliases: [qpunish, punish]
    permission: quantumpunish.admin
  ban:
    description: Ban a player
    permission: quantumpunish.ban
  tempban:
    description: Temporarily ban a player
    permission: quantumpunish.tempban
  unban:
    description: Unban a player
    permission: quantumpunish.unban
  banip:
    description: Ban an IP address
    permission: quantumpunish.banip
  unbanip:
    description: Unban an IP address
    permission: quantumpunish.unbanip
  mute:
    description: Mute a player
    permission: quantumpunish.mute
  tempmute:
    description: Temporarily mute a player
    permission: quantumpunish.tempmute
  unmute:
    description: Unmute a player
    permission: quantumpunish.unmute
  kick:
    description: Kick a player
    permission: quantumpunish.kick
  warn:
    description: Warn a player
    permission: quantumpunish.warn
  history:
    aliases: [punishhistory, phistory]
    description: View punishment history
    permission: quantumpunish.history
  playerinfo:
    aliases: [qinfo]
    description: View player information
    permission: quantumpunish.info
  appeal:
    description: Submit an appeal if you are muted
    permission: quantumpunish.appeal
    usage: /appeal <reason>
  jail:
    description: Jail a player with labor requirements
    permission: quantumpunish.jail
    usage: /jail <player> <duration> <cell> <labor> <reason>

  unjail:
    description: Release a player from jail
    permission: quantumpunish.unjail
    usage: /unjail <player>

  jailstatus:
    description: Check jail status
    permission: quantumpunish.jailstatus
    usage: /jailstatus [player]

  jailadmin:
    description: Manage jail cells and spawners
    permission: quantumpunish.jail.admin
    usage: /jailadmin <setcell|removecell|listcells|setspawner|removespawner|listspawners|setrelease>
    aliases: [ jadmin ]

permissions:
  quantumpunish.*:
    description: All
  quantumpunish.appeal:
    description: Allows submitting an appeal
    default: true
  quantumpunish.jail:
    description: Allows jailing players
    default: op
  quantumpunish.unjail:
    description: Allows releasing players from jail
    default: op
  quantumpunish.jailstatus:
    description: Allows checking own jail status
    default: true
  quantumpunish.jailstatus.others:
    description: Allows checking others' jail status
    default: op
  quantumpunish.jail.admin:
    description: Allows managing jail system
    default: op